name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: rssletter-py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push image
      uses: docker/build-push-action@v1
      with:
        repository: vaayne/rssletter-py
        username: ${{ secrets.DOCKER_USERNAME }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tag_with_ref: true
        push:: true
